using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace NFramework.Mediator.Mediator.Railway.UnionRailway.Generator;

/// <summary>
/// Emits closed <c>IPipelineBehavior</c> registrations for every concrete request that implements
/// <c>IRailRequest&lt;TValue&gt;</c>, so the railway validation behavior can be resolved without
/// runtime reflection or open-generic substitution.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class RailwayRegistrationGenerator : IIncrementalGenerator
{
    private const string GeneratedNamespace = "NFramework.Mediator.Mediator.Railway.UnionRailway";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<RailRequestModel> requests = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is TypeDeclarationSyntax { BaseList: not null },
                transform: static (ctx, _) => Map(ctx)
            )
            .Where(static model => model is not null)
            .Select(static (model, _) => model!.Value);

        IncrementalValueProvider<ImmutableArray<RailRequestModel>> collected = requests.Collect();

        context.RegisterSourceOutput(collected, static (productionContext, models) => Emit(productionContext, models));
    }

    private static RailRequestModel? Map(GeneratorSyntaxContext context)
    {
        if (context.Node is not TypeDeclarationSyntax declaration)
        {
            return null;
        }

        if (context.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        if (symbol.IsAbstract || symbol.IsGenericType)
        {
            return null;
        }

        foreach (INamedTypeSymbol interfaceSymbol in symbol.AllInterfaces)
        {
            if (interfaceSymbol.MetadataName == "IRailRequest`1"
                && interfaceSymbol.ContainingNamespace.ToDisplayString() == GeneratedNamespace
                && interfaceSymbol.TypeArguments.Length == 1)
            {
                string request = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                string value = interfaceSymbol.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                return new RailRequestModel(request, value);
            }
        }

        return null;
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<RailRequestModel> models)
    {
        ImmutableArray<RailRequestModel> distinct = [.. models.Distinct()];

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using Mediator;");
        builder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        builder.AppendLine();
        builder.AppendLine($"namespace {GeneratedNamespace};");
        builder.AppendLine();
        builder.AppendLine("/// <summary>Generated closed registrations for railway validation behaviors.</summary>");
        builder.AppendLine("public static class RailwayGeneratedRegistration");
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>Registers a railway validation behavior for each discovered IRailRequest type.</summary>");
        builder.AppendLine("    public static IServiceCollection AddNFrameworkRailwayValidation(this IServiceCollection services)");
        builder.AppendLine("    {");
        builder.AppendLine("        System.ArgumentNullException.ThrowIfNull(services);");
        builder.AppendLine();

        foreach (RailRequestModel model in distinct)
        {
            builder.AppendLine(
                $"        services.AddTransient<IPipelineBehavior<{model.RequestType}, global::UnionRailway.Rail<{model.ValueType}>>, "
                    + $"global::{GeneratedNamespace}.RailValidationBehavior<{model.RequestType}, {model.ValueType}>>();"
            );
        }

        builder.AppendLine();
        builder.AppendLine("        return services;");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        context.AddSource("RailwayGeneratedRegistration.g.cs", builder.ToString());
    }

    private readonly struct RailRequestModel(string requestType, string valueType)
        : IEquatable<RailRequestModel>
    {
        public string RequestType { get; } = requestType;

        public string ValueType { get; } = valueType;

        public bool Equals(RailRequestModel other) =>
            RequestType == other.RequestType && ValueType == other.ValueType;

        public override bool Equals(object? obj) => obj is RailRequestModel other && Equals(other);

        public override int GetHashCode() =>
            unchecked((RequestType.GetHashCode() * 397) ^ ValueType.GetHashCode());
    }
}
